name: Validate pull request before putting into queue

on:
  pull_request:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Display info
      run: | 
        pwd
        tree -a -I '.git'
        git status
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Run fast CI (emulated by a short sleep)
      run: sleep 5