# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'
        
env:
    APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    APPLITOOLS_BATCH_NAME: ${{ github.ref }}
    APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha || github.sha }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo BRANCH_NAME="##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Log  Git SHA
        run: echo GITHUB_SHA="$GITHUB_SHA"
      - name: Log env
        run: env
      - name: Log  "{{ github.event.pull_request.head.sha }}"
        run: echo ${{ github }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci
      - name: Prepare for push event may be use BranchName=${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}
        run: curl -v -L -d '' -X POST "https://testeyes.applitools.com/api/externals/github/push?apiKey=${APPLITOOLS_API_KEY}&CommitSha=${GITHUB_SHA}&BranchName=${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}"
      - name: Run Tests
        run: npm test
      - name: Comlete GitHub check
        run: echo AutoCompleteEnabled#curl -v -L -d '' -X POST "https://testeyes.testeyesapi.applitools.com/api/externals/github/servers/github.com/commit/${APPLITOOLS_BATCH_ID}/complete?apiKey=${APPLITOOLS_API_KEY}"
        
